name: wc_assignment
description: A new Flutter project
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  flutter_bloc: ^8.1.1
  firebase_core: ^2.4.0
  cloud_firestore: ^4.2.0
  equatable: ^2.0.5
  flutter_spinkit: ^5.1.0
  image_picker: ^0.8.6
  cached_network_image: ^3.2.3
  firebase_storage: ^11.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

  fonts:
    - family: Exo
      fonts:
        - asset: assets/fonts/Exo-Regular.ttf
          style: normal
        - asset: assets/fonts/Exo-Italic.ttf
          style: italic
        - asset: assets/fonts/Exo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Exo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Exo-Black.ttf
          weight: 900
        - asset: assets/fonts/Exo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Exo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Exo-Light.ttf
          weight: 300
        - asset: assets/fonts/Exo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Exo-Thin.ttf
          weight: 100
